name: material
description: Set of material design icons packed in a single ttf font file. Works on all platforms.
version: 1.0.0+1
homepage: https://pwa.ir
repository: https://github.com/xclud/flutter_material

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 fonts:
   - family: Material
     fonts:
       - asset: lib/fonts/material.ttf
